name: rtDataVis
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python = 3.12
  - pandas
  - xarray
  - scipy
  - numpy
  - scikit-learn
  - matplotlib
  - gsw
  - cmocean
  - google-crc32c
  - google-cloud-secret-manager
  - pyyaml
  - pyodbc
  - pip:
      - basemap
      - basemap-data
      - basemap-data-hires
      - dbdreader
      - glider-utils